### ISSUE TITLE
Not work to build using release 7.6.2, Currently

### ISSUE THREAD

**Issue by seungyongshim** [elastic/elastic-stack-installers#67]
Excuse, me.

Use by https://github.com/elastic/elastic-stack-installers/releases/tag/v7.6.2
```
PS C:\git2020\elastic-stack-installers-7.6.2> ./build build --cid 7.6.2 filebeat-oss
ElastiBuild: BuildBeatPackageCompiler: Succeeded. (5.36 s)
ElastiBuild: FindPackage#filebeat-oss: Starting...
Searching local directory C:\git2020\elastic-stack-installers-7.6.2\bin\in ...
Searching Artifacts API for filebeat-oss-7.6.2 ...
ElastiBuild: FindPackage#filebeat-oss: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask)
   at ElastiBuild.Infra.ArtifactsApi.FindArtifact(String target, Action`1 filterConfiguration) in C:\git2020\elastic-stack-installers-7.6.2\src\build\Infra\ArtifactsApi.cs:line 72
   at ElastiBuild.BullseyeTargets.FindPackageTarget.RunAsync(BuildContext ctx, String targetName) in C:\git2020\elastic-stack-installers-7.6.2\src\build\BullseyeTargets\FindPackageTarget.cs:line 79
   at ElastiBuild.Commands.BuildCommand.<>c__DisplayClass24_0.<<RunAsync>b__2>d.MoveNext() in C:\git2020\elastic-stack-installers-7.6.2\src\build\Commands\BuildCommand.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Bullseye.Internal.ActionTarget.RunAsync(Boolean dryRun, Boolean parallel, Logger log, Func`2 messageOnly)
ElastiBuild: FindPackage#filebeat-oss: Failed! Response status code does not indicate success: 404 (Not Found). (1.02 s)
ElastiBuild: ──────────────────────────────────────────────────
ElastiBuild: Duration       Outcome    Target
ElastiBuild: ─────────────  ─────────  ────────────────────────
ElastiBuild: 1.02 s  16.0%  Failed!    FindPackage#filebeat-oss
ElastiBuild: 5.36 s  84.0%  Succeeded  BuildBeatPackageCompiler
ElastiBuild: ──────────────────────────────────────────────────
ElastiBuild: Failed! (BuildInstaller#filebeat-oss) (
```

- Broken link to artifact host for beats, isn't it?
- When recover to host?

Please, help me. My boss is going to happy.

Regards.

**Comment by ygel** [comment]
Hello @seungyongshim. 

First, let me mention that we support only installers built by our release process. Download page for official filebeat-oss is here: https://www.elastic.co/downloads/beats/filebeat-oss

That said, there's no "container" named 7.6.2. When running `discover containers` command like shown below, there's a more general `7.6` container and more speciic `7.6.3-SNAPSHOT` alias:
```shell
$ ./build discover containers

Branches:
  master
  7.x
  7.8
  7.7
  7.6
  6.8

Versions:
  6.8.9-SNAPSHOT
  6.8.9
  7.6.3-SNAPSHOT
  7.7.0-SNAPSHOT
  7.7.0
  7.8.0-SNAPSHOT
  7.8.0
  7.9.0-SNAPSHOT
  8.0.0-SNAPSHOT

Aliases:
  6.8-SNAPSHOT
  6.8
  7.x-SNAPSHOT
  7.6-SNAPSHOT
  7.7-SNAPSHOT
  7.7
  7.8-SNAPSHOT
  7.8
  8.0-SNAPSHOT
```

If you modify your command like shown below, you'll be able to build `7.6.3-SNAPSHOT`:
```shell
./build build --cid 7.6 filebeat-oss
```

**Comment by seungyongshim** [comment]
Thank you. My problem was solve, partially. To use `./build build --cid 7.6.3 filebeat-oss`, I will.

I have a quetion.

## Important idempotent
- I agree `we support only installers built by our release process`. But, important idempotent.
- 20 days ago, my github actions was working. But now that is broken. Because it remove 7.6.2 on artifact server by your company policy.
- I would like to ask you a favor. When I leave my job, I don't want to answer a beginner's phone call.

Regards
